# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


def forwards_func(apps, schema_editor):
    Template = apps.get_model("video_app", "Template")
    db_alias = schema_editor.connection.alias
    Template.objects.using(db_alias).create(name='intel_kate')


def reverse_func(apps, schema_editor):
    Template = apps.get_model("video_app", "Template")
    db_alias = schema_editor.connection.alias
    Template.objects.using(db_alias).filter(name='intel_kate').delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.UUIDField(default=uuid.uuid4, verbose_name='name')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
                ('file', models.FileField(upload_to='csv_files', verbose_name='file')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveSmallIntegerField(verbose_name='line number')),
                ('error', models.CharField(default='', max_length=128, verbose_name='error')),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows',
                                               to='video_app.CsvFile', verbose_name='csv file')),
            ],
            options={
                'ordering': ('csv_file', 'line'),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TextDataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='name')),
                ('value', models.CharField(default='', max_length=256, verbose_name='value')),
                ('data_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts',
                                               to='video_app.DataRow', verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.UUIDField(default=uuid.uuid4, verbose_name='file name')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='last time')),
                ('status', models.CharField(
                    choices=[('0', 'Created'), ('1', 'In queue'), ('2', 'Active'), ('3', 'Ready'), ('4', 'Error')],
                    default='0', max_length=1, verbose_name='status')),
                ('video_file', models.FileField(upload_to=b'', verbose_name='video file')),
                ('thumbnail_file', models.ImageField(upload_to=b'', verbose_name='thumbnail file')),
                ('data_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos',
                                               to='video_app.DataRow', verbose_name='data row')),
            ],
            options={
                'ordering': ('-last_time', '-datetime'),
            },
        ),
        migrations.AddField(
            model_name='csvfile',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files',
                                    to='video_app.Template'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
